"""Add template_reply_to and reply_to_message_id to Message

Revision ID: 065247aa21fd
Revises: cf0db4353355
Create Date: 2025-08-08 16:21:11.297844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '065247aa21fd'
down_revision: Union[str, None] = 'cf0db4353355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('template_status', postgresql.ENUM('approved', 'pending', 'rejected', name='template_status_enum'), nullable=True))
    op.add_column('messages', sa.Column('failure_reason', postgresql.ENUM('unapproved_template', 'user_opted_out', 'invalid_phone', name='failure_reason_enum'), nullable=True))
    op.add_column('messages', sa.Column('template_reply_to', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('reply_to_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('messages', 'template_reply_to')
    op.drop_column('messages', 'failure_reason')
    op.drop_column('messages', 'template_status')
    # ### end Alembic commands ###
