"""Add appointment tracking fields to referrer_tracking

Revision ID: 09945250a609
Revises: ba4179abdd6f
Create Date: 2025-09-29 11:02:20.754672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09945250a609'
down_revision: Union[str, None] = 'ba4179abdd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_products_name_cat_sub_lower'), table_name='products')
    op.add_column('referrer_tracking', sa.Column('appointment_date', sa.DateTime(), nullable=True))
    op.add_column('referrer_tracking', sa.Column('appointment_time', sa.String(), nullable=True))
    op.add_column('referrer_tracking', sa.Column('treatment_type', sa.String(), nullable=True))
    op.add_column('referrer_tracking', sa.Column('is_appointment_booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer_tracking', 'is_appointment_booked')
    op.drop_column('referrer_tracking', 'treatment_type')
    op.drop_column('referrer_tracking', 'appointment_time')
    op.drop_column('referrer_tracking', 'appointment_date')
    op.create_index(op.f('uq_products_name_cat_sub_lower'), 'products', [sa.literal_column('lower(name::text)'), 'category_id', 'sub_category_id'], unique=True)
    # ### end Alembic commands ###
