"""Add last_attempted_by and last_triggered_time to Job

Revision ID: 0fe12361be93
Revises: a7549b9e4157
Create Date: 2025-07-15 12:15:17.081383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe12361be93'
down_revision: Union[str, None] = 'a7549b9e4157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('last_attempted_by', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('last_triggered_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['last_attempted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'last_triggered_time')
    op.drop_column('jobs', 'last_attempted_by')
    # ### end Alembic commands ###
