"""add location column to leads table

Revision ID: 0ff9256c9d00
Revises: add_leads_manual
Create Date: 2025-10-28 16:16:07.573682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff9256c9d00'
down_revision: Union[str, None] = 'add_leads_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('location', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('leads_zoho_lead_id_key'), 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_zoho_lead_id'), table_name='leads')
    op.create_index(op.f('ix_leads_zoho_lead_id'), 'leads', ['zoho_lead_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_zoho_lead_id'), table_name='leads')
    op.create_index(op.f('ix_leads_zoho_lead_id'), 'leads', ['zoho_lead_id'], unique=False)
    op.create_unique_constraint(op.f('leads_zoho_lead_id_key'), 'leads', ['zoho_lead_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('leads', 'location')
    # ### end Alembic commands ###
