"""Add order status and payment tracking fields

Revision ID: 28938eb38a5f
Revises: b8294813e5e2
Create Date: 2025-10-25 15:45:07.247858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28938eb38a5f'
down_revision: Union[str, None] = 'b8294813e5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('payment_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_completed_at')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
