"""added new column roles to the users table

Revision ID: 29d30980540d
Revises: da2808dbdddb
Create Date: 2025-07-08 12:08:10.879541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '29d30980540d'
down_revision: Union[str, None] = 'da2808dbdddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = ENUM('ADMIN', 'AGENT', name='user_role_enum')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='user_role_enum'),server_default='AGENT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
