"""Add ON DELETE CASCADE to jobs status

Revision ID: 2d9fad3fe207
Revises: 515ee8f2048b
Create Date: 2025-06-27 15:56:54.399056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9fad3fe207'
down_revision: Union[str, None] = '515ee8f2048b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_status_job_id_fkey'), 'job_status', type_='foreignkey')
    op.create_foreign_key(None, 'job_status', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_status', type_='foreignkey')
    op.create_foreign_key(op.f('job_status_job_id_fkey'), 'job_status', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
