"""Add content and type to campaigns

Revision ID: 2ed07fd203e8
Revises: 099538a46dd9
Create Date: 2025-06-24 16:43:35.767654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ed07fd203e8'
down_revision: Union[str, None] = '099538a46dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

campaign_type_enum = postgresql.ENUM(
    'text', 'image', 'document', 'template', 'interactive',
    name='campaign_type_enum'
)

def upgrade() -> None:
    """Upgrade schema."""
    campaign_type_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('type', postgresql.ENUM('text', 'image', 'document', 'template', 'interactive', name='campaign_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'type')
    op.drop_column('campaigns', 'content')
    campaign_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
