"""Add new column created at for customers

Revision ID: 2f7381a9b9eb
Revises: 2d9fad3fe207
Create Date: 2025-06-27 17:43:34.095450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7381a9b9eb'
down_revision: Union[str, None] = '2d9fad3fe207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
