"""new table and format to store templates

Revision ID: 382b5c4a7399
Revises: 8536bbc8efd7
Create Date: 2025-06-26 12:35:12.092365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '382b5c4a7399'
down_revision: Union[str, None] = '8536bbc8efd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('template_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
