"""Remove UTM tracking fields from referrer_tracking table

Revision ID: 42cf65164bae
Revises: 09945250a609
Create Date: 2025-09-30 10:49:39.987824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cf65164bae'
down_revision: Union[str, None] = '09945250a609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrer_tracking', 'utm_campaign')
    op.drop_column('referrer_tracking', 'referrer_url')
    op.drop_column('referrer_tracking', 'utm_content')
    op.drop_column('referrer_tracking', 'utm_source')
    op.drop_column('referrer_tracking', 'utm_medium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrer_tracking', sa.Column('utm_medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('referrer_tracking', sa.Column('utm_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('referrer_tracking', sa.Column('utm_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('referrer_tracking', sa.Column('referrer_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('referrer_tracking', sa.Column('utm_campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
