"""Added logs table

Revision ID: 4c7be847f287
Revises: 64df909b6012
Create Date: 2025-11-11 17:32:53.522310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7be847f287'
down_revision: Union[str, None] = '64df909b6012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('user_ip', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('wa_id', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_logs_created_at'), 'flow_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_flow_logs_flow_run_id'), 'flow_logs', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_flow_logs_mobile'), 'flow_logs', ['mobile'], unique=False)
    op.create_index(op.f('ix_flow_logs_request_id'), 'flow_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_flow_logs_wa_id'), 'flow_logs', ['wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_logs_wa_id'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_request_id'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_mobile'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_flow_run_id'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_created_at'), table_name='flow_logs')
    op.drop_table('flow_logs')
    # ### end Alembic commands ###
