"""Add ON DELETE CASCADE to jobs.campaign_id

Revision ID: 515ee8f2048b
Revises: f6c0a0ac142f
Create Date: 2025-06-27 15:54:25.002471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515ee8f2048b'
down_revision: Union[str, None] = 'f6c0a0ac142f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
