"""Add last_job_id to campaigns

Revision ID: 6e71d2fec03e
Revises: 0fe12361be93
Create Date: 2025-07-15 12:23:10.398428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e71d2fec03e'
down_revision: Union[str, None] = '0fe12361be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('last_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'jobs', ['last_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'last_job_id')
    # ### end Alembic commands ###
