"""Add customer_status enum column

Revision ID: 6eca50d3043d
Revises: c99caf7de9c4
Create Date: 2025-07-24 13:09:52.861117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eca50d3043d'
down_revision: Union[str, None] = 'c99caf7de9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_status', sa.Enum('pending', 'open', 'resolved', name='customer_status_enum'), nullable=True))
    op.drop_column('customers', 'center_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('center_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'customer_status')
    # ### end Alembic commands ###
