"""add_zoho_mapping_table

Revision ID: 75c80dc2ffd4
Revises: 28938eb38a5f
Create Date: 2025-10-27 21:22:30.549539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c80dc2ffd4'
down_revision: Union[str, None] = '28938eb38a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoho_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('zoho_name', sa.String(length=255), nullable=False),
    sa.Column('zoho_sub_concern', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_mappings_treatment_name'), 'zoho_mappings', ['treatment_name'], unique=True)
    op.create_index(op.f('ix_zoho_mappings_zoho_name'), 'zoho_mappings', ['zoho_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_mappings_zoho_name'), table_name='zoho_mappings')
    op.drop_index(op.f('ix_zoho_mappings_treatment_name'), table_name='zoho_mappings')
    op.drop_table('zoho_mappings')
    # ### end Alembic commands ###
