"""Add fix nullable status

Revision ID: 824aabf88610
Revises: 6eca50d3043d
Create Date: 2025-07-24 13:10:58.875501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '824aabf88610'
down_revision: Union[str, None] = '6eca50d3043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'customer_status',
               existing_type=postgresql.ENUM('pending', 'active', 'resolved', name='customer_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'customer_status',
               existing_type=postgresql.ENUM('pending', 'active', 'resolved', name='customer_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
