"""last message should be tracked from now [customers] table

Revision ID: 8bcbb6f19f4c
Revises: 2f7381a9b9eb
Create Date: 2025-07-02 17:38:07.403072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcbb6f19f4c'
down_revision: Union[str, None] = '2f7381a9b9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_message_at')
    # ### end Alembic commands ###
