"""add notification fields to payments

Revision ID: 8fdf575f2aca
Revises: 9522ddf76ac8
Create Date: 2025-09-16 10:37:26.773191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdf575f2aca'
down_revision: Union[str, None] = '9522ddf76ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'notification_sent')
    # ### end Alembic commands ###
