"""Removed some columns and add some

Revision ID: 981458db74d2
Revises: 4c7be847f287
Create Date: 2025-11-11 18:48:14.179976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '981458db74d2'
down_revision: Union[str, None] = '4c7be847f287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_logs', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_flow_logs_flow_run_id'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_mobile'), table_name='flow_logs')
    op.drop_index(op.f('ix_flow_logs_request_id'), table_name='flow_logs')
    op.drop_column('flow_logs', 'meta')
    op.drop_column('flow_logs', 'user_ip')
    op.drop_column('flow_logs', 'country_code')
    op.drop_column('flow_logs', 'flow_run_id')
    op.drop_column('flow_logs', 'event_type')
    op.drop_column('flow_logs', 'mobile')
    op.drop_column('flow_logs', 'channel')
    op.drop_column('flow_logs', 'message')
    op.drop_column('flow_logs', 'sender')
    op.drop_column('flow_logs', 'phone_number_id')
    op.drop_column('flow_logs', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_logs', sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('phone_number_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('sender', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('channel', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('mobile', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('flow_run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('country_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('user_ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('flow_logs', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_flow_logs_request_id'), 'flow_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_flow_logs_mobile'), 'flow_logs', ['mobile'], unique=False)
    op.create_index(op.f('ix_flow_logs_flow_run_id'), 'flow_logs', ['flow_run_id'], unique=False)
    op.drop_column('flow_logs', 'name')
    # ### end Alembic commands ###
