"""Cascade delete campaigns when user is deleted

Revision ID: a8b9dbd17591
Revises: 8bcbb6f19f4c
Create Date: 2025-07-04 15:33:13.969007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b9dbd17591'
down_revision: Union[str, None] = '8bcbb6f19f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_created_by_fkey'), 'campaigns', type_='foreignkey')
    op.drop_constraint(op.f('campaigns_updated_by_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'campaigns', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_updated_by_fkey'), 'campaigns', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('campaigns_created_by_fkey'), 'campaigns', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
