"""Add media fields to messages

Revision ID: a9536d9f64c8
Revises: 32aa104349b2
Create Date: 2025-06-18 15:54:53.098932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9536d9f64c8'
down_revision: Union[str, None] = '32aa104349b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('caption', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'mime_type')
    op.drop_column('messages', 'filename')
    op.drop_column('messages', 'caption')
    op.drop_column('messages', 'media_id')
    # ### end Alembic commands ###
