"""add new fields to order table

Revision ID: b8294813e5e2
Revises: 42cf65164bae
Create Date: 2025-10-24 12:58:19.336071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8294813e5e2'
down_revision: Union[str, None] = '42cf65164bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new boolean column with default value False for existing rows
    op.add_column(
        'order_items',
        sa.Column(
            'is_modification_addition',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    op.add_column(
        'order_items',
        sa.Column('modification_timestamp', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'orders',
        sa.Column('modification_started_at', sa.DateTime(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'modification_started_at')
    op.drop_column('order_items', 'modification_timestamp')
    op.drop_column('order_items', 'is_modification_addition')
    # ### end Alembic commands ###
