"""Fix Customer ↔ CustomerAddress relationships

Revision ID: c6ba53a6f411
Revises: a0d109782e8d
Create Date: 2025-09-22 13:00:21.783135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ba53a6f411'
down_revision: Union[str, None] = 'a0d109782e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('default_address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'customers', 'customer_addresses', ['default_address_id'], ['id'])
    op.drop_column('customers', 'address')
    op.add_column('orders', sa.Column('shipping_address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_id')
    op.add_column('customers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'default_address_id')
    # ### end Alembic commands ###
