"""FIX:ALEMBIC

Revision ID: c8016b95f81c
Revises: 1035aa95dabe
Create Date: 2025-08-11 15:28:11.908207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8016b95f81c'
down_revision: Union[str, None] = '1035aa95dabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('messages', 'template_reply_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('template_reply_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('reply_to_message_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
