"""update message model

Revision ID: cf0db4353355
Revises: 2bbbcd4bcab2
Create Date: 2025-08-05 13:22:05.925056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0db4353355'
down_revision: Union[str, None] = '2bbbcd4bcab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('center_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('agent_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('sender_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_type')
    op.drop_column('messages', 'agent_id')
    op.drop_column('messages', 'center_id')
    # ### end Alembic commands ###
