"""drop description and lead_status columns from leads table

Revision ID: cf10ad5521af
Revises: 0ff9256c9d00
Create Date: 2025-10-28 16:35:16.209557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf10ad5521af'
down_revision: Union[str, None] = '0ff9256c9d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'description')
    op.drop_column('leads', 'lead_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
