"""add address column to customers

Revision ID: d242918cbb54
Revises: 29d30980540d
Create Date: 2025-07-08 15:49:41.573107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd242918cbb54'
down_revision: Union[str, None] = '29d30980540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('template_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('var_name', sa.String(), nullable=False),
    sa.Column('var_val', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('message_id', 'template_id', 'var_name', name='template_message_pk')
    )
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_wa_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.add_column('customers', sa.Column('wa_id', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_unique_constraint(None, 'customers', ['wa_id'])
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'phone')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('customers', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'wa_id')
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wa_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_messages_pkey')),
    sa.UniqueConstraint('message_id', name=op.f('whatsapp_messages_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_whatsapp_messages_wa_id'), 'whatsapp_messages', ['wa_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.drop_table('template_messages')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
