"""add address column to customers

Revision ID: d242918cbb54
Revises: 29d30980540d
Create Date: 2025-07-08 15:49:41.573107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd242918cbb54'
down_revision: Union[str, None] = '29d30980540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('customers', 'address')

    # ### end Alembic commands ###
