"""added relationship b/w users and customers

Revision ID: da2808dbdddb
Revises: a8b9dbd17591
Create Date: 2025-07-07 13:33:05.296118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2808dbdddb'
down_revision: Union[str, None] = 'a8b9dbd17591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
