"""add primary concern and sub_source column in lead table

Revision ID: df2591058689
Revises: cf10ad5521af
Create Date: 2025-10-28 16:39:21.453075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2591058689'
down_revision: Union[str, None] = 'cf10ad5521af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('primary_concern', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('sub_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'sub_source')
    op.drop_column('leads', 'primary_concern')
    # ### end Alembic commands ###
