"""fix campaign to handle jobs delete

Revision ID: eb4975d59520
Revises: 60bd03af5863
Create Date: 2025-06-27 15:39:28.687335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4975d59520'
down_revision: Union[str, None] = '60bd03af5863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_campaign_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_campaign_id_fkey'), 'jobs', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
