"""Add campaign_cost_type to Campaign

Revision ID: f2b35c2efeac
Revises: 0d838e03d0f4
Create Date: 2025-07-14 15:54:32.582891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b35c2efeac'
down_revision: Union[str, None] = '0d838e03d0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('campaigns', sa.Column('campaign_cost_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'costs', ['campaign_cost_type'], ['type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'campaign_cost_type')

