"""Add template column in message table

Revision ID: f37dcbd8510f
Revises: c8016b95f81c
Create Date: 2025-08-18 13:26:45.555004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f37dcbd8510f'
down_revision: Union[str, None] = 'c8016b95f81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('template_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('template_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'template_params')
    op.drop_column('messages', 'template_name')
    # ### end Alembic commands ###
