"""Remove template column from message table

Revision ID: f6705d74a22c
Revises: f37dcbd8510f
Create Date: 2025-08-18 14:00:27.520886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6705d74a22c'
down_revision: Union[str, None] = 'f37dcbd8510f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'template_params')
    op.drop_column('messages', 'template_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('template_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
