"""Add ON DELETE CASCADE to jobs.campaign_id

Revision ID: f6c0a0ac142f
Revises: fb3eca9b4349
Create Date: 2025-06-27 15:51:46.207790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c0a0ac142f'
down_revision: Union[str, None] = 'fb3eca9b4349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
