"""campaign delete cascade feature

Revision ID: fb3eca9b4349
Revises: 4c566ba34f81
Create Date: 2025-06-27 15:48:41.029052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3eca9b4349'
down_revision: Union[str, None] = '4c566ba34f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_status_customer_id_fkey'), 'job_status', type_='foreignkey')
    op.create_foreign_key(None, 'job_status', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_status', type_='foreignkey')
    op.create_foreign_key(op.f('job_status_customer_id_fkey'), 'job_status', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
